version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/ajunquit/index.json
    username: ajunquit
    password: ${{secrets.GH_PACKAGES_TOKEN}}

updates:
  - package-ecosystem: nuget
    directory: "/src/UNIR.TFE.Polyrepo.Addition.Module"
    registries: ["github"]
    schedule:
      interval: daily
    allow:
      - dependency-name: "UNIR.TFE.Polyrepo.Shared"   # usa el mismo nombre que en tu .csproj
    target-branch: main
