version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"  # carpeta que contiene el .csproj
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["dependencies", "nuget"]
