version: 2

registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/ajunquit/index.json
    username: ajunquit
    password: ${{secrets.GH_PACKAGES_TOKEN}}

updates:
  - package-ecosystem: "nuget"
    directory: "/"                # cambia si tu .csproj vive en /src u otra carpeta
    registries: ["github"]
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "unir.tfe.polyrepo.shared"
    open-pull-requests-limit: 5
    labels: ["dependencies", "nuget"]
    target-branch: "main"

