# .github/dependabot.yml
version: 2

registries:
  gh:
    type: nuget-feed
    url: https://nuget.pkg.github.com/<OWNER>/index.json
    username: ajunquit
    password: ${{secrets.GH_PACKAGES_TOKEN}}  # token con read:packages

updates:
  - package-ecosystem: "nuget"
    directory: "/src/UNIR.TFE.Polyrepo.Addition.Module"
    schedule:
      interval: "daily"
    registries: ["gh"]
